sonar.projectKey=Aplicativo_Java
sonar.projectName=Mi proyecto basado en java y html
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/.git/**
sonar.java.binaries=target/classes
