sonar.projectKey=mac-stev1996_Aplicativo_Java_c7e97964-ff9c-489f-b145-aa03bc730586
sonar.projectName=Mi proyecto basado en java y html
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9002
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/build/**,**/.git/**,**/*.min.js
sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/test/**,**/tests/**
sonar.test.exclusions=**/node_modules/**,**/target/**
sonar.xml.file.suffixes=.xml,.xhtml
