name: SonarQube Analysis
 
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:
  build-and-analyze:
    name: Build and SonarQube Scan
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # SonarQube necesita el historial completo para el análisis de "novedades" (New Code)
          fetch-depth: 0
 
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
 
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
 
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
 
      - name: Build, test and run SonarQube analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: 'sqp_38d5f9c21024fc49782a4a435f3d18f05e29cf23'
        run: >
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=mac-stev1996_Aplicativo_Java_c7e97964-ff9c-489f-b145-aa03bc730586
          -Dsonar.host.url= 'http://127.0.0.1:9002'
          -Dsonar.token= 'sqp_38d5f9c21024fc49782a4a435f3d18f05e29cf23'
 
      - name: Check SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: 'sqp_38d5f9c21024fc49782a4a435f3d18f05e29cf23'
          SONAR_HOST_URL: 'http://127.0.0.1:9002'
